name: habit_app
description: ردیاب روزانه ورزش، درس و قرص
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  shamsi_date: ^1.0.1

flutter:
  uses-material-design: true
